# Generated by Django 4.1.5 on 2023-01-20 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('style', models.CharField(choices=[('POP', 'Pop'), ('RAP', 'Rap'), ('CLASSIC', 'Classic'), ('ROCK', 'Rock'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chanson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('duree', models.DurationField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp1.artiste')),
            ],
        ),
    ]
