# Generated by Django 4.1.5 on 2023-01-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanson',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myApp1.artiste'),
        ),
    ]
